import type { Prize } from '@/types/prize'

export const PRIZES: Prize[] = [
  {
    id: 'iphone-17-pro-max',
    label: 'Grand Prize',
    shortLabel: 'iPhone 17 Pro Max',
    wheelLabel: ['IPHONE 17', 'PRO MAX'],
    amount: 'iPhone 17 Pro Max',
    probability: 0,
    angle: 0,
    className: 'iphone',
  },
  {
    id: 'cash-100',
    label: 'Cash Prize',
    shortLabel: '₱100',
    wheelLabel: ['₱100'],
    amount: '₱100',
    probability: 5,
    angle: 60,
    className: '',
  },
  {
    id: 'cash-50',
    label: 'Cash Prize',
    shortLabel: '₱50',
    wheelLabel: ['₱50'],
    amount: '₱50',
    probability: 10,
    angle: 120,
    className: '',
  },
  {
    id: 'cash-30',
    label: 'Cash Prize',
    shortLabel: '₱30',
    wheelLabel: ['₱30'],
    amount: '₱30',
    probability: 25,
    angle: 180,
    className: '',
  },
  {
    id: 'cash-20',
    label: 'Cash Prize',
    shortLabel: '₱20',
    wheelLabel: ['₱20'],
    amount: '₱20',
    probability: 50,
    angle: 240,
    className: '',
  },
  {
    id: 'angpow',
    label: 'Random Angpow',
    shortLabel: 'Angpow',
    wheelLabel: ['ANGPOW'],
    amount: '₱10–₱50',
    probability: 10,
    angle: 300,
    className: 'angpow',
  },
]
